FROM ros:humble-ros-base-jammy

# Make sure bash catches errors
SHELL ["/bin/bash", "-o", "pipefail", "-o", "errexit", "-c"]


# 1.) Bring system up to the latest ROS desktop configuration
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install ros-humble-desktop

# 2.) Temporarily remove ROS2 apt repository
RUN mv /etc/apt/sources.list.d/ros2.sources /root/
RUN apt-get update

# 3.) comment out the catkin conflict
RUN sed  -i -e 's|^Conflicts: catkin|#Conflicts: catkin|' /var/lib/dpkg/status
RUN apt-get install -f

# 4.) force install these packages
RUN apt-get download python3-catkin-pkg
RUN apt-get download python3-rospkg
RUN apt-get download python3-rosdistro
RUN dpkg --force-overwrite -i python3-catkin-pkg*.deb
RUN dpkg --force-overwrite -i python3-rospkg*.deb
RUN dpkg --force-overwrite -i python3-rosdistro*.deb
RUN apt-get install -f

# 5.) Install the latest ROS1 desktop configuration
RUN apt-get -y install ros-desktop-dev

# fix ARM64 pkgconfig path issue -- Fix provided by ambrosekwok
RUN if [[ $(uname -m) = "arm64" || $(uname -m) = "aarch64" ]]; then                     \
      cp /usr/lib/x86_64-linux-gnu/pkgconfig/* /usr/lib/aarch64-linux-gnu/pkgconfig/;   \
    fi

# 6.) Restore the ROS2 apt repos and set compilation options.
RUN mv /root/ros2.sources /etc/apt/sources.list.d/
RUN apt-get -y update
# 6.1) Add ROS1 ros_tutorials messages and services
RUN git clone -b noetic-devel --depth=1 https://github.com/ros/ros_tutorials.git;     \
    cd ros_tutorials;                                                                 \
    unset ROS_DISTRO;                                                                 \
    time colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release;                        \
    # for actionlib_tutorials                                                         \
    cd ..;                                                                            \
    source ros_tutorials/install/setup.bash;                                          \
    git clone -b fuerte-devel --depth=1 https://github.com/ros/common_tutorials.git;  \
    cd common_tutorials;                                                              \
    unset ROS_DISTRO;                                                                 \
    time colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release;

# 6.3) Compile custom message (code provided by Codaero)
RUN git clone https://github.com/JPGC04/custom_ros.git;       \
      # Compile for ROS1:                                               \
      cd /custom_ros/catkin_ws/src/auv_msgs;                                 \
      unset ROS_DISTRO;                                                 \
      time colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release;        \
      # Compile for ROS2:                                               \
      cd /custom_ros/colcon_ws/src/auv_msgs;                                 \
      source /opt/ros/humble/setup.bash;                                \
      time colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release;

# 7.) Compile ros1_bridge
RUN source /opt/ros/humble/setup.bash;                                                          \
    source ros_tutorials/install/setup.bash;                                                  \
    source common_tutorials/install/setup.bash;                                                  \
    apt-get -y install ros-humble-example-interfaces ros-humble-action-tutorials-interfaces;  \
    apt-get -y install ros-humble-action-tutorials-cpp ros-humble-action-tutorials-py;        \
    source /opt/ros/humble/setup.bash;								\

    ls -la /custom_ros/catkin_ws/; \

    source /custom_ros/catkin_ws/src/auv_msgs/install/setup.bash;                                  \
    source /custom_ros/colcon_ws/src/auv_msgs/install/setup.bash;                                  \
    
    # Finally, build the Bridge                                                                 \
    mkdir -p /ros-humble-ros1-bridge/src;                                                       \
    cd /ros-humble-ros1-bridge/src;                                                             \
    git clone -b action_bridge_humble --depth=1 https://github.com/smith-doug/ros1_bridge.git;  \
    cd ros1_bridge/;                                                                            \
    cd ../..;                                                                                   \
    MEMG=$(printf "%.0f" $(free -g | awk '/^Mem:/{print $2}'));                                 \
    NPROC=$(nproc);  MIN=$((MEMG<NPROC ? MEMG : NPROC));                                        \
    #                                                                                           \
    echo "Please wait...  running $MIN concurrent jobs to build ros1_bridge";                   \
    time MAKEFLAGS="-j $MIN" colcon build --event-handlers console_direct+                      \
      --cmake-args -DCMAKE_BUILD_TYPE=Release

# 8.) Clean up
RUN apt-get -y clean all; apt-get -y update

# 9.) Pack all ROS1 dependent libraries
# fix ARM64 pkgconfig path issue -- Fix provided by ambrosekwok
RUN if [[ $(uname -m) = "arm64" || $(uname -m) = "aarch64" ]]; then                    \
      cp /usr/lib/x86_64-linux-gnu/pkgconfig/* /usr/lib/aarch64-linux-gnu/pkgconfig/;  \
    fi

RUN ROS1_LIBS="libxmlrpcpp.so";                                                 \
     ROS1_LIBS="$ROS1_LIBS librostime.so";                                      \
     ROS1_LIBS="$ROS1_LIBS libroscpp.so";                                       \
     ROS1_LIBS="$ROS1_LIBS libroscpp_serialization.so";                         \
     ROS1_LIBS="$ROS1_LIBS librosconsole.so";                                   \
     ROS1_LIBS="$ROS1_LIBS librosconsole_log4cxx.so";                           \
     ROS1_LIBS="$ROS1_LIBS librosconsole_backend_interface.so";                 \
     ROS1_LIBS="$ROS1_LIBS liblog4cxx.so";                                      \
     ROS1_LIBS="$ROS1_LIBS libcpp_common.so";                                   \
     ROS1_LIBS="$ROS1_LIBS libb64.so";                                          \
     ROS1_LIBS="$ROS1_LIBS libaprutil-1.so";                                    \
     ROS1_LIBS="$ROS1_LIBS libapr-1.so";                                        \
     ROS1_LIBS="$ROS1_LIBS libactionlib.so.1d";                                 \
     cd /ros-humble-ros1-bridge/install/ros1_bridge/lib;                        \
     for soFile in $ROS1_LIBS; do                                               \
       soFilePath=$(ldd libros1_bridge.so | grep $soFile | awk '{print $3;}');  \
       cp $soFilePath ./;                                                       \
     done

# 10.) Spit out ros1_bridge tarball by default when no command is given
RUN tar czf /ros-humble-ros1-bridge.tgz \
     --exclude '*/build/*' --exclude '*/src/*' /ros-humble-ros1-bridge
ENTRYPOINT []
CMD cat /ros-humble-ros1-bridge.tgz; sync